# Config file for lazygit
#
# Need to run:
#     ln -fs config.yml $HOME/Library/Application\ Support/lazygit/
# 
# Global config file at:
#
# > MacOS: $HOME/Library/Application\ Support/lazygit/config.yml
# > Linux: $HOME/.config/lazygit/config.yml
# > Windows: %LOCALAPPDATA%\lazygit\config.yml or %APPDATA%\lazygit\config.yml
# 
# Below setting ref to:
#     https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium (Jun 29, 2022)
#
# Default setting:
#     https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
# ----------------------------------------------------------------------------
#
# set diff format highlight, firstly install:
# > cp /usr/local/Cellar/git/2.26.2/share/git-core/contrib/diff-highlight/diff-highlight /usr/local/bin/
git:
  paging:
    colorArg: always
    #pager: delta --paging=never --24-bit-color=never
    pager: diff-highlight
#git:
#  paging:
#    externalDiffCommand: difft --color=always --display=inline --syntax-highlight=off
confirmOnQuit: true
notARepository: quit
promptToReturnFromSubprocess: false # display confirmation when subprocess terminates
gui:
  scrollHeight: 15 # how many lines you scroll by
#-------------------- below are custom key --------------------
# Extract diff into index
# This requires some explanation: say you've got a PR that has merged in master
# a few times and so it's a bit of a mess to follow the changes, but there's
# actually not that many lines changed in total. In that case, you probably
# just want to take the actual changes and put them in a single commit on top
# of the head of the master branch.
customCommands:
  - key: 'D'
    command: git diff {{.SelectedLocalBranch.Name}} > /tmp/lazygit.patch && git reset --hard {{.SelectedLocalBranch.Name}} && git apply /tmp/lazygit.patch
    context: localBranches
    description: Extract diff into index
    # Amend the author of last commit
  - key: '<c-a>'
    description: 'amend the author of last commit'
    command: 'git commit --amend --author="{{index .PromptResponses 0}} <{{index .PromptResponses 1}}>"'
    context: 'commits'
    prompts:
      - type: 'input'
        title: 'Author Name'
        initialValue: ''
      - type: 'input'
        title: 'Email Address'
  - key: b
    command: tig blame -- {{.SelectedFile.Name}}
    context: files
    description: blame file at worktree
    output: terminal
  - key: b
    command: tig blame {{.SelectedSubCommit.Sha}} -- {{.SelectedCommitFile.Name}}
    context: commitFiles
    description: blame file at revision
    output: terminal
  - key: B
    command: tig blame -- {{.SelectedCommitFile.Name}}
    context: commitFiles
    description: blame file at worktree
    output: terminal
  - key: t
    command: tig show {{.SelectedSubCommit.Sha}}
    context: subCommits
    description: tig commit (`t` again to browse files at revision)
    output: terminal
  - key: t
    command: tig show {{.SelectedLocalBranch.Name}}
    context: localBranches
    description: tig branch (`t` again to browse files at revision)
    output: terminal
  - key: t
    command: tig show {{.SelectedRemoteBranch.RemoteName}}/{{.SelectedRemoteBranch.Name}}
    context: remoteBranches
    description: tig branch (`t` again to browse files at revision)
    output: terminal
  - key: t
    command: tig {{.SelectedSubCommit.Sha}} -- {{.SelectedCommitFile.Name}}
    context: commitFiles
    description: tig file (history of commits affecting file)
    output: terminal
  - key: t
    command: tig -- {{.SelectedFile.Name}}
    context: files
    description: tig file (history of commits affecting file)
    output: terminal
